import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {fixture} from './fixtures.mjs';
import {importLegacy} from '../server/importer.mjs';
import {openStore} from '../server/store.mjs';
import {createApi} from '../server/api.mjs';
test('HTTP API persists validated edits and serves seekable copied media',async t=>{
 const f=fixture(t);await importLegacy(f.source,f.dest);const store=openStore(f.dest);
 const middleware=createApi(store);const server=createServer((req,res)=>middleware(req,res,()=>{res.writeHead(404);res.end()}));
 server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(r=>server.close(r));store.close()});
 const base=`http://127.0.0.1:${server.address().port}`;
 const saved=await (await fetch(base+'/api/annotations')).json();assert.equal(saved.schemaVersion,2);assert.equal(saved.revision,12);
 const partial=await fetch(base+'/media/01',{headers:{Range:'bytes=2-5'}});assert.equal(partial.status,206);assert.equal(await partial.text(),'smal');
 assert.equal((await fetch(base+'/media/01',{method:'HEAD'})).headers.get('content-length'),String(f.media.length));
 assert.equal((await fetch(base+'/media/01',{headers:{Range:'bytes=999-'}})).status,416);
 const put=(body,origin=base)=>fetch(base+'/api/annotations',{method:'PUT',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)});
 assert.equal((await put(saved,'https://foreign.invalid')).status,403);
 assert.equal((await put({...saved,episodes:[{...saved.episodes[0],endFrame:999}]})).status,400);
 assert.equal((await put({...saved,episodes:[{...saved.episodes[0],note:'changed'}]})).status,200);
 assert.equal((await put(saved)).status,409);
 assert.equal((await (await fetch(base+'/api/annotations')).json()).episodes[0].note,'changed');
 assert.equal((await fetch(base+'/api/frames/unknown')).status,404);
});
