import test from 'node:test';import assert from 'node:assert/strict';
import {validate} from '../scripts/personal-video-review-assets/core.mjs';
const sha='a'.repeat(64),dataset='b'.repeat(64),items=[{id:sha,sha256:sha}];
const record={id:sha,sha256:sha,element:'2A',rotation:'short',athleteGroup:null};
const payload=labels=>({schemaVersion:1,datasetSha256:dataset,labels});
test('accept explicit answers and optional anonymous group',()=>{assert.deepEqual(validate(payload([record]),items,dataset),[record]);assert.equal(validate(payload([{...record,element:'other',rotation:null,athleteGroup:' S01 '}]),items,dataset)[0].athleteGroup,'S01');});
test('reject duplicate, unknown identity and hash mismatch',()=>{for(const labels of [[record,record],[{...record,id:'unknown'}],[{...record,sha256:'c'.repeat(64)}]])assert.throws(()=>validate(payload(labels),items,dataset));});
test('reject wrong dataset and crossfield answers',()=>{assert.throws(()=>validate({...payload([record]),datasetSha256:'x'},items,dataset));for(const r of [{...record,element:''},{...record,rotation:null},{...record,element:'other'},{...record,element:'unclear',rotation:'complete'},{...record,athleteGroup:3}])assert.throws(()=>validate(payload([r]),items,dataset));});
test('unanswered is not an expert answer; unclear type requires null rotation',()=>{assert.deepEqual(validate(payload([]),items,dataset),[]);assert.equal(validate(payload([{...record,element:'unclear',rotation:null}]),items,dataset)[0].rotation,null);});
test('reject group control characters before trimming',()=>{for(const athleteGroup of [' S01\n','S\t01','S\x0001','\rS01'])assert.throws(()=>validate(payload([{...record,athleteGroup}]),items,dataset));});
