"""Report distinguishes automatic proposal from user-confirmed contact."""
import html,json

def render(result,frames):
 label=html.escape(result['typeProposal'].get('predicted_label') or 'Недостаточно данных')
 names={'apparently_complete':'Предположительно докручен','apparently_short':'Предположительно недокручен',None:'Требуется подтверждение касания / достаточная видимость'}
 verdict=names[result.get('rotationAssessment')]
 seen='<p>Этот ролик входил в обучение модели типа. Он не является независимой проверкой.</p>' if result.get('typeSeenTrainingClip') else ''
 contact=result.get('contactProposal') or {};initial=result.get('userConfirmedContactFrame',contact.get('predictedFirstContact')) or 0
 frame_data=[{'n':r['frameIndex'],'image':result.get('landmarksDirectory','landmarks')+'/'+r['image'],'sourceFrame':r.get('sourceFrameIndex'),'time':r.get('sourceTime',r.get('time'))} for r in frames]
 controls=''
 if frames and result['typeProposal'].get('predicted_label')=='2A':
  controls='''<h2>Подтвердите первое касание</h2><p>Выберите первый кадр, где конёк коснулся льда. Точки конька будут пересчитаны вокруг выбранного кадра.</p><img id="contact-image" alt="Кадр для проверки касания"><div><button id="prev">−1 кадр</button><input id="frame" aria-label="Кадр касания" type="range" min="0" max="'''+str(len(frames)-1)+'''" value="'''+str(min(initial,len(frames)-1))+'''"><button id="next">+1 кадр</button></div><p id="frame-label"></p><button id="confirm" disabled>Подтвердить касание и получить подсказку</button><p id="status" role="status"></p>'''
  controls+='''<script>const frames='''+json.dumps(frame_data).replace('<','\\u003c')+r''';const slider=document.querySelector('#frame'),picture=document.querySelector('#contact-image'),confirm=document.querySelector('#confirm'),status=document.querySelector('#status');let epoch=0;async function show(){const token=++epoch;confirm.disabled=true;const r=frames[Number(slider.value)],image=new Image();image.src=r.image;try{await image.decode();if(token!==epoch)return;picture.src=image.src;document.querySelector('#frame-label').textContent=`Кадр ${r.n}, исходный кадр ${r.sourceFrame}, время ${Number(r.time).toFixed(3)} с`;confirm.disabled=false;}catch(e){if(token===epoch)status.textContent='Не удалось загрузить кадр';}}slider.oninput=show;document.querySelector('#prev').onclick=()=>{slider.value=Math.max(0,Number(slider.value)-1);show()};document.querySelector('#next').onclick=()=>{slider.value=Math.min(frames.length-1,Number(slider.value)+1);show()};confirm.onclick=async()=>{const id=location.pathname.match(/\/runs\/([a-f0-9-]+)\//)?.[1];if(!id){status.textContent='Подтверждение доступно в загрузчике на порту5196';return}confirm.disabled=true;try{const response=await fetch('/confirm/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({frame:frames[Number(slider.value)].n})});const body=await response.json();if(!response.ok)throw Error(body.error);let state;do{status.textContent='Пересчитываю точки конька…';await new Promise(r=>setTimeout(r,2000));state=await(await fetch('/status/'+id)).json()}while(state.status==='processing');if(state.status==='error')throw Error(state.error);location.reload()}catch(e){status.textContent=e.message;confirm.disabled=false}};show();</script>'''
 return '''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FS_elem · результат</title><style>body{font:18px system-ui;background:#101923;color:#eef;max-width:1000px;margin:25px auto;padding:20px}video{width:100%;max-height:45vh}#contact-image{display:block;width:100%;height:50vh;object-fit:contain;background:#000}p{line-height:1.5}button{font:inherit;padding:12px;margin:5px}input{width:40%}a{color:#8df}</style><h1>Предложение типа: '''+label+'''</h1><video controls src="sample.mp4"></video><h2>'''+verdict+'''</h2>'''+seen+'''<p>Автоматический вердикт без подтверждения касания отключён. Надёжное определение докрута на новых спортсменах и съёмках пока не подтверждено. Результат остаётся предварительной подсказкой для проверки тренером.</p><p>Фактическое число оборотов и угол недокрута пока не измеряются. Число в названии класса не является измерением вращения.</p>'''+controls+'''<p><a href="result.json">Результат и версии моделей</a></p></html>'''
