import {layout,project} from './identity-core.mjs';
const $=id=>document.getElementById(id);
let episodes=[],current=0,index=0,playing=false,playToken=0,renderToken=0;
const images=new Map();
const episode=()=>episodes[current];
function stop(){playing=false;playToken++;$('play').textContent='Смотреть эпизод';}
function image(url){if(!images.has(url)){if(images.size>30)images.delete(images.keys().next().value);images.set(url,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>{images.delete(url);reject(Error('Кадр не загрузился. Выберите его повторно.'))};im.src=url}));}return images.get(url);}
function draw(id,im,points,crop){const ctx=$(id).getContext('2d'),t=layout(crop);ctx.fillStyle='#070c10';ctx.fillRect(0,0,640,640);ctx.drawImage(im,-crop[0]*t.scale+t.x,-crop[1]*t.scale+t.y,1280*t.scale,720*t.scale);if(!$('skeleton').checked)return;const map=Object.fromEntries(points.map(p=>[p.name,p]));for(const side of ['left','right']){ctx.strokeStyle=ctx.fillStyle=side==='left'?'#ff79d3':'#61dcff';ctx.lineWidth=2;for(const [a,b] of [['shoulder','elbow'],['elbow','wrist'],['shoulder','hip'],['hip','knee'],['knee','ankle']]){const p=map[side+'_'+a],q=map[side+'_'+b];if(!p||!q)continue;const u=project(p,crop),v=project(q,crop);ctx.beginPath();ctx.moveTo(u.x,u.y);ctx.lineTo(v.x,v.y);ctx.stroke();}for(const part of ['shoulder','elbow','wrist','hip','knee','ankle']){const p=map[side+'_'+part];if(!p)continue;const v=project(p,crop);ctx.beginPath();ctx.arc(v.x,v.y,3,0,Math.PI*2);ctx.fill();}}}
async function render(){const token=++renderToken,e=episode(),f=e.frames[index];$('status').textContent='Загрузка пары…';try{const im=await image(f.image);if(token!==renderToken)return;draw('raw',im,f.raw,e.crop);draw('proposed',im,f.proposed,e.crop);$('scrub').value=index;$('frame').textContent=`${e.athlete} · кадр ${f.frameIndex} · ${f.time.toFixed(3)} с`;$('prev').disabled=index===0;$('next').disabled=index===e.frames.length-1;const changed=f.frameIndex>=e.startFrame&&f.frameIndex<=e.endFrame;$('status').textContent=changed?`Справа изменены названия сторон: ${e.region==='legs'?'тазобедренные суставы, колени и голеностопы':'плечи, локти и запястья'}. Требуется визуальная проверка.`:'Контекстный кадр: исходная модель и предложение совпадают.';}catch(error){if(token===renderToken){stop();$('status').textContent=error.message;}}}
function select(n){stop();current=n;index=0;const e=episode();$('episode').value=n;$('scrub').max=e.frames.length-1;$('prevEpisode').disabled=n===0;$('nextEpisode').disabled=n===episodes.length-1;$('explanation').textContent=`${e.attemptId} · ${e.region==='legs'?'Ноги':'Руки'} · предложение для кадров ${e.startFrame}–${e.endFrame}. Проверяем весь эпизод вместе с соседними кадрами.`;render();}
function seek(n){stop();index=Math.max(0,Math.min(episode().frames.length-1,n));render();}
$('episode').onchange=()=>select(Number($('episode').value));$('prevEpisode').onclick=()=>select(current-1);$('nextEpisode').onclick=()=>select(current+1);$('prev').onclick=()=>seek(index-1);$('next').onclick=()=>seek(index+1);$('scrub').oninput=()=>seek(Number($('scrub').value));$('skeleton').onchange=()=>render();
$('play').onclick=async()=>{if(playing){stop();return;}playing=true;const token=++playToken;$('play').textContent='Пауза';index=0;while(playing&&token===playToken){await render();await new Promise(r=>setTimeout(r,200));if(!playing||token!==playToken)break;if(index===episode().frames.length-1){stop();break;}index++;}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
try{const response=await fetch('identity-review.json',{cache:'no-store'});if(!response.ok)throw Error('Не удалось загрузить эпизоды');({episodes}=await response.json());if(!episodes.length)throw Error('Нет предложений для просмотра');episodes.forEach((e,i)=>{const option=document.createElement('option');option.value=i;option.textContent=`${e.athlete} · ${e.startFrame}–${e.endFrame} · ${e.region==='legs'?'ноги':'руки'}`;$('episode').append(option);});$('episode').disabled=false;select(Math.max(0,episodes.findIndex(e=>e.attemptId==='competition-47-03-01'&&e.startFrame===3651)));}catch(error){$('status').textContent=error.message;document.querySelectorAll('button,input,select').forEach(e=>e.disabled=true);}
