import {Flag,Undo2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Episode} from '@/lib/annotation-types';
const time=(x:number|null)=>x===null?'—':`${Math.floor(x/60).toString().padStart(2,'0')}:${(x%60).toFixed(3).padStart(6,'0')}`;
export function EpisodePanel({list,episode,active,patch,onSelect,onRemove,canUndo,onUndo,axelOnly=false}:{list:Episode[];episode:Episode|undefined;active:string;patch:(data:Partial<Episode>)=>void;onSelect:(episode:Episode)=>void;onRemove:()=>void;canUndo:boolean;onUndo:()=>void;axelOnly?:boolean}){return <section className="annotations"><div className="library-head"><span className="eyebrow">РАЗМЕТКА</span><span>{list.length}</span></div><h2>{axelOnly?'Аксели':'Эпизоды'}</h2><p className="muted">{axelOnly?'Сначала проверьте предложенный фрагмент, затем уточните границы по кадрам.':'Каждый прыжок отметьте отдельно.'}</p><div className="episode-list">{list.length===0?<div className="empty"><Flag size={25}/><p>Найдите отрыв от льда и нажмите «Начало прыжка».</p></div>:list.map((e,i)=><button key={e.id} className={'episode '+(e.id===active?'active':'')} onClick={()=>onSelect(e)}><span>{e.protocolCode?`№${e.protocolElementSequence} · ${e.protocolCode}`:`Эпизод ${i+1}`}<small>{e.start!==null&&e.end!==null?(axelOnly?'Границы предложены':'Отмечен'):axelOnly&&e.analysisProposal?.windowStart!=null?'Окно найдено':axelOnly?'В поиске':'Черновик'}</small></span><strong>{time(e.start)} → {time(e.end)}</strong></button>)}</div>
    {episode?<div className="details">{axelOnly?<div className="axel-call"><strong>Протокол: {episode.protocolCode||'—'}</strong><small>Официальная запись элемента, не вывод из видео</small><label>Оценка по видео<select value={episode.analysisProposal?.call||''} onChange={e=>patch({analysisProposal:{confidence:'low',reason:episode.analysisProposal?.reason||'Оценка изменена при проверке в редакторе.',source:'visual_review',...episode.analysisProposal,call:e.target.value||undefined}})}><option value="">Не определено</option><option value="без знака">Без знака</option><option value="q">q — четверть</option><option value="&lt;">&lt; — недокрут</option><option value="&lt;&lt;">&lt;&lt; — понижение</option></select></label><small>{episode.analysisProposal?.reason||'Визуальная проверка приземления ожидает анализа.'}</small></div>:null}<label>Группа одной попытки<input value={episode.attemptGroup||''} placeholder="Например: Ханю-01" maxLength={100} onChange={e=>patch({attemptGroup:e.target.value})}/></label><p className="muted">Одинаковое имя для повторов одного прыжка.</p><label>Комментарий<textarea value={episode.note} maxLength={5000} placeholder="Ракурс, замедление, спорный момент…" onChange={e=>patch({note:e.target.value})}/></label><Button variant="ghost" onClick={onRemove}>Убрать эпизод</Button></div>:null}
    {canUndo?<Button variant="outline" onClick={onUndo}><Undo2/> Отменить изменение</Button>:null}
    <div className="local-note"><span className="dot"/>Локальная работа<p>Отметки сохраняются на этом компьютере. Я смогу прочитать их в нашей задаче.</p></div>
   </section>;}
